CREATE TABLE IF NOT EXISTS `project_construction_record` (
  `tenant`                             varchar(50)    NOT NULL                   COMMENT '租户code' ,
  `org_id`                             bigint         NOT NULL    DEFAULT 0      COMMENT '组织ID、或项目id' ,
  `id`                                 bigint         NOT NULL                   COMMENT 'id' ,
  `weather`                            varchar(50)                               COMMENT '天气' ,
  `temperature`                        varchar(50)                               COMMENT '温度' ,
  `record_time`                        datetime       NOT NULL                   COMMENT '记录时间' ,
  `commit_time`                        datetime                                  COMMENT '提交时间' ,
  `number_of_comments`                 bigint         NOT NULL    DEFAULT 0      COMMENT '评论数' ,
  `number_of_readers`                  bigint         NOT NULL    DEFAULT 0      COMMENT '已读数' ,
  `status`                             varchar(50)    NOT NULL    DEFAULT 'uncommitted' COMMENT '状态，默认未提交' ,
  `source_type`                        varchar(50)                               COMMENT '记录来源' ,
  `summarize`                          longtext                                  COMMENT '记录文字' ,
  `creator`                            bigint         NOT NULL    DEFAULT 0      COMMENT '记录创建人，提交人' ,
  `created_at`                         datetime       NOT NULL                   COMMENT '记录创建时间，提交时间' ,
  `reviser`                            bigint         NOT NULL    DEFAULT 0      COMMENT '记录修改人' ,
  `updated_at`                         datetime       NOT NULL                   COMMENT '记录修改时间' ,
  `is_removed`                         boolean        NOT NULL    DEFAULT FALSE  COMMENT '删除标记' ,
  `version`                            bigint         NOT NULL                   COMMENT '记录版本号' ,
  `project_construction_record_adjustment_id` bigint                                    COMMENT '调差单据id' ,
  `approval_status`                    varchar(50)                               COMMENT '单据审批状态:reject被拒;approved:通过;underReview审批中;cancel取消审核',
  PRIMARY KEY (`tenant`,`org_id`,`id`) 
)  COMMENT='现场施工记录';


CREATE TABLE IF NOT EXISTS `project_construction_record_detail` (
  `tenant`                             varchar(50)    NOT NULL                   COMMENT '租户code' ,
  `org_id`                             bigint         NOT NULL    DEFAULT 0      COMMENT '组织ID、或项目id' ,
  `id`                                 bigint         NOT NULL                   COMMENT 'id' ,
  `project_construction_record_id`     bigint         NOT NULL                   COMMENT '主表id' ,
  `content`                            varchar(16383)                            COMMENT '记录内容' ,
  `ext_content`                        longtext                                  COMMENT '记录内容扩展' ,
  `record_type`                        varchar(50)                               COMMENT '记录类型' ,
  `level`                              bigint         NOT NULL    DEFAULT 1      COMMENT '层级' ,
  `order_no`                           bigint         NOT NULL                   COMMENT '排序号' ,
  `parent_id`                          bigint         NOT NULL                   COMMENT '父记录id' ,
  `full_id`                            varchar(2000)  NOT NULL                   COMMENT 'ID全路径' ,
  `full_id_ex`                         varchar(2000)  NOT NULL                   COMMENT 'ID全路径' ,
  `creator`                            bigint         NOT NULL    DEFAULT 0      COMMENT '记录创建人，提交人' ,
  `created_at`                         datetime       NOT NULL                   COMMENT '记录创建时间，提交时间' ,
  `reviser`                            bigint         NOT NULL    DEFAULT 0      COMMENT '记录修改人' ,
  `updated_at`                         datetime       NOT NULL                   COMMENT '记录修改时间' ,
  `is_removed`                         boolean        NOT NULL    DEFAULT FALSE  COMMENT '删除标记' ,
  `version`                            bigint         NOT NULL                   COMMENT '记录版本号' ,
  `project_labor_team_id`              bigint                                    COMMENT '队伍id' ,
  `project_spot_id`                    bigint                                    COMMENT '工点id' ,
  `entry_work_id`                      bigint                                    COMMENT '分部分项id',
  PRIMARY KEY (`tenant`,`org_id`,`id`) 
)  COMMENT='现场施工记录详情';


CREATE TABLE IF NOT EXISTS `project_construction_record_procedure_detail` (
  `tenant`                             varchar(50)    NOT NULL                   COMMENT '租户code' ,
  `org_id`                             bigint         NOT NULL    DEFAULT 0      COMMENT '组织ID、或项目id' ,
  `id`                                 bigint         NOT NULL                   COMMENT 'id' ,
  `project_construction_record_id`     bigint         NOT NULL                   COMMENT '施工记录主表id' ,
  `project_construction_record_detail_id` bigint         NOT NULL                   COMMENT '施工记录id' ,
  `project_spot_id`                    bigint         NOT NULL                   COMMENT '工点id' ,
  `project_labor_team_id`              bigint                                    COMMENT '施工队伍id' ,
  `project_part_id`                    bigint                                    COMMENT '部位id' ,
  `project_spot_progress_custom_part_id` bigint                                    COMMENT '自定义部位id' ,
  `progress_item_id`                   bigint                                    COMMENT '形象进度项id' ,
  `progress_item_procedure_detail_id`  bigint         NOT NULL                   COMMENT '记录字段id' ,
  `material_id`                        bigint                                    COMMENT '材料id' ,
  `value`                              varchar(2000)                             COMMENT '值' ,
  `ext_value`                          varchar(2000)                             COMMENT '扩展值' ,
  `creator`                            bigint         NOT NULL    DEFAULT 0      COMMENT '记录创建人，提交人' ,
  `created_at`                         datetime       NOT NULL                   COMMENT '记录创建时间，提交时间' ,
  `reviser`                            bigint         NOT NULL    DEFAULT 0      COMMENT '记录修改人' ,
  `updated_at`                         datetime       NOT NULL                   COMMENT '记录修改时间' ,
  `is_removed`                         boolean        NOT NULL    DEFAULT FALSE  COMMENT '删除标记' ,
  `version`                            bigint         NOT NULL                   COMMENT '记录版本号' ,
  `entry_work_id`                                 bigint                                            COMMENT '分部分项id',
  `entry_work_procedure_template_detail_id`       bigint                                            COMMENT '分项工序施工记录模板记录字段id' ,
  `project_spot_entry_work_custom_part_id`        bigint                                            COMMENT '分项自定义部位id',
  `standard_construction_method_part_id`         bigint                                            COMMENT '开挖支护工法部位id',
  PRIMARY KEY (`tenant`,`org_id`,`id`) 
)  COMMENT='施工记录工序记录字段历史详情';


CREATE TABLE IF NOT EXISTS `project_construction_record_progress_quantity` (
  `tenant`                             varchar(50)    NOT NULL                   COMMENT '租户code' ,
  `org_id`                             bigint         NOT NULL    DEFAULT 0      COMMENT '组织ID、或项目id' ,
  `id`                                 bigint         NOT NULL                   COMMENT 'id' ,
  `project_construction_record_id`     bigint         NOT NULL                   COMMENT '记录id' ,
  `project_construction_record_detail_id` bigint                                    COMMENT '记录详情id' ,
  `project_unit_work_id`               bigint                                    COMMENT '单位工程id' ,
  `stat_year`                          bigint                                    COMMENT '统计年' ,
  `stat_month`                         bigint                                    COMMENT '统计月' ,
  `project_spot_id`                    bigint         NOT NULL                   COMMENT '工点id' ,
  `project_labor_team_id`              bigint         NOT NULL                   COMMENT '队伍id' ,
  `project_part_id`                    bigint                                    COMMENT '部位id' ,
  `progress_item_id`                   bigint         NOT NULL                   COMMENT '形象进度项id' ,
  `progress_item_procedure_id`         bigint                                    COMMENT '工序id' ,
  `progress_item_procedure_detail_id`  bigint                                    COMMENT '详情id' ,
  `construction_location`              varchar(2000)                             COMMENT '施工位置' ,
  `start_pile`                         varchar(255)                              COMMENT '开始桩号' ,
  `end_pile`                           varchar(255)                              COMMENT '结束桩号' ,
  `quantity`                           decimal(18, 6)                     DEFAULT 0      COMMENT '本次完成形象量' ,
  `stat_quantity`                      decimal(18, 6)                     DEFAULT 0      COMMENT '本次完成统计量' ,
  `amount`                             decimal(18, 2)                     DEFAULT 0      COMMENT '本次完成产值' ,
  `start_time`                         datetime                                  COMMENT '开始时间' ,
  `end_time`                           datetime                                  COMMENT '完成时间' ,
  `complete_percent`                   decimal(18, 2)                                    COMMENT '本次完成占比' ,
  `design_amount`                      decimal(18, 2)                                     ,
  `stated_amount`                      decimal(18, 2)                                     ,
  `stating_amount`                     decimal(18, 2)                                     ,
  `adjusted_amount`                    decimal(18, 2)                                     ,
  `status`                             varchar(50)                DEFAULT 'todo' COMMENT '完成状态,' ,
  `progress_quantity_type`             varchar(50)                               COMMENT '形象量类型:spotProgress工点形象进度;spotPartProgress工点部位形象进度' ,
  `creator`                            bigint         NOT NULL    DEFAULT 0      COMMENT '记录创建人' ,
  `created_at`                         datetime       NOT NULL                   COMMENT '记录创建时间' ,
  `reviser`                            bigint         NOT NULL    DEFAULT 0      COMMENT '记录修改人' ,
  `updated_at`                         datetime       NOT NULL                   COMMENT '记录修改时间' ,
  `version`                            bigint         NOT NULL                   COMMENT '记录版本号' ,
  `is_removed`                         boolean        NOT NULL    DEFAULT FALSE  COMMENT '删除标记' ,
  `design_quantity`                    decimal(18, 6)                                    comment '形象量设计量',
  `design_stat_quantity`               decimal(18, 6)                                    comment '统计量设计量'
  `entry_work_property_id`             bigint                                    COMMENT '部位按属性细分后的属性id' ,
  `entry_work_property_value`          varchar(50)                               COMMENT '部位按属性细分后的属性值' ,
  `project_spot_progress_custom_part_id` bigint                                    COMMENT '自定义或拆分的部位id' ,
  `entry_work_id`                                 bigint                                            COMMENT '分部分项id',
  `entry_work_procedure_id`                       bigint                                            COMMENT '分项工序id',
  `standard_construction_method_part_id`          bigint                                            COMMENT '开挖支护工法部位id',
  `project_spot_entry_work_custom_part_id`        bigint                                            COMMENT '分项自定义部位id',
  `expired_status`                     varchar(50)                              comment '作废状态：committed已提交申请，underReview：审批中,expired:作废',
  `project_divisional_work_id`         bigint                                   comment '工程实体分项id',
  `procedure_percent`                  DECIMAL(5,2)                             comment '工序完成比例',
  `divided_part_percent`               DECIMAL(5,2)                             comment '拆分部位所占比例',
  `pile_no_prefix`                     varchar(50)                              comment '桩号前缀',
  `start_pile_no`                      DECIMAL(18,6)                            comment '开始桩号',
  `end_pile_no`                        DECIMAL(16,6)                            comment '结束桩号'
  `side`                                  varchar(50)                                     COMMENT '路面分项的幅别'
  PRIMARY KEY (`tenant`,`org_id`,`id`) 
)  COMMENT='现场施工记录形象量记录';